python3 train_condition_distill.py \
    --cuda True \
    --gpu_ids 0 \
    --name CCG1 \
    --keep_step 30000 \
    --Ddownx2 \
    --Ddropout \
    --lasttvonly \
    --interflowloss \
    --occlusion \
    --TConditionG_ckpt ./checkpoints/conditionG-tea/mtviton.pth \
    --TConditionD_ckpt ./checkpoints/conditionD-tea/discriminator_mtviton.pth
